/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/watch_model.glb --transform --keepmeshes --R 2048 
Files: public/watch_model.glb [7.01MB] > C:\Users\danie\OneDrive\Documents\GitHub\Geez-watch\watch_model-transformed.glb [823.7KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { ThinGlassMaterial } from './Brandmaterial'

export function Watch_model(props) {
  const { nodes, materials } = useGLTF('/watch_model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['strap-metal_Baked'].geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.hodlder_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.stich_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.bar_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.glass_Baked.geometry}><ThinGlassMaterial/></mesh>
      <mesh geometry={nodes.goma_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.spil_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      {/* <mesh geometry={nodes.strap_gold_Baked.geometry} material={materials['MergedBake_Baked.014']} /> */}
      {/* <mesh geometry={nodes.strap_leather_Baked.geometry} material={materials['MergedBake_Baked.014']} /> */}
      <mesh geometry={nodes.top_metal_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.volume_Baked.geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes.hand_hour_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hand_minute_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hand_second_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_1001_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_10_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_12_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_1_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_2_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_3_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_4_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_5_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_6_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_7_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_8_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.hour_9_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes.inside_Baked.geometry} material={materials['MergedBake_Baked.014']} position={[0, -0.391, 0]} />
      <mesh geometry={nodes['bottom-metal_2_Baked'].geometry} material={materials['MergedBake_Baked.014']} />
      <mesh geometry={nodes['bottom-metal_Baked'].geometry} material={materials['MergedBake_Baked.014']} />
    </group>
  )
}

useGLTF.preload('/watch_model-transformed.glb')
